controller:
  kind: DaemonSet
  replicaCount: 2
#  resources:
#    requests:
#      cpu: "100m"
#      memory: "64Mi"
#    limits:
#      cpu: "500m"
#      memory: "128Mi"
  reportNodeInternalIp: true
  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443
  service:
    type: NodePort
    use-forwarded-headers: "true"
